### PR TITLE
Feature/add laravel5.8 support

### PR DESCRIPTION
**Pull request by jimmypuckett**

### CODE REVIEW

**Comment by jimmypuckett** [comment]
@ssfinney I am starting pulling up the key packages to 5.8.  There is some interesting things that we need to consider.

For example `phpunit 8` sets a return type of `:void` on `setUp()`, so any test that is extending it needs to be adjusted.  That is not that bad, but it means that the code will not work on `php 5.x`, which technically, the package works back to `Laravel 5.1`, so we need to decide what to do.

Should we start next major version & only go back to version of Laravel that supports `php 7.1`?

**Comment by jimmypuckett** [comment]
@ssfinney I am going to make this `2.x` branch support `php >= is 7.2` to allow `phpunit 8`. If someone needs older version of php, then they can stick with `1.x`

**Comment by jimmypuckett** [comment]
@ssfinney This is ready to merge. Can you look it over in the morning? I would like to tag it as v2 tomorrow to have it ready for 5.8.  I will then do a similar thing with the other packages.

**Review by ssfinney — APPROVED** [review]
Looks good except for the Scrutinizer question

**Comment by ssfinney** [comment]
@jimmypuckett Coveralls is having issues: http://status.coveralls.io/

**Comment by jimmypuckett** [comment]
Great



-jimmy
478-314-2636 (o/f)

**Comment by jimmypuckett** [comment]
@ssfinney I have removed coveralls & changed to just using Scrutinizer for reporting coverage. I have Travis sending the coverage files. Also, I switched to `phpdbg`.

I have removed coveralls in their site, but it is still here as a required check.

I am force merging anyhow.

I hope that new PR's will not have the check?

**Pull request merged**
