### PR TITLE
Feature/support5.6

### PR DESCRIPTION
**Pull request by jimmypuckett**

### CODE REVIEW

**Comment by jimmypuckett** [comment]
@ssfinney This is ready when you are ready to review it.  As we discussed, when we tag it, lets move to the next major version.

**Comment by ssfinney** [comment]
@jimmypuckett Scrutinizer timed out (you can probably just re-push and it might clear). Code coverage also failed since it dipped below 100. Anything we can do about that?

**Comment by ssfinney** [comment]
@jimmypuckett This one is failing on code coverage being <100%

**Comment by jimmypuckett** [comment]
@ssfinney I am not exactly sure why those 2 inspections are failing.  I forced the merge.

**Comment by ssfinney** [comment]
@jimmypuckett Coveralls failed because the coverage dipped below 100%. Shouldn't we make a test for that?

**Pull request merged**
